name: Build Executables

on:
  push:
  workflow_dispatch:

env:
  # OSX complains if it's 0.x.x
  APP_VERSION: 1.0.0
  JAVA_VERSION: 17

jobs:
  ##########
  # WINDOWS
  ##########
  build-windows:
    name: Build executable for Windows
    runs-on: windows-latest
    steps:
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v2
    - id: setup-jdk
      name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - id: build
      name: Build distribution
      run: |
        gradle -v
        gradle build
        jpackage --verbose "@config/jpackage.cfg" "@config/jpackage-windows.cfg" --app-version ${{ env.APP_VERSION }}
    - id: upload
      name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        path: ./build/distributions/windows
        name: windows-executable
        retention-days: 1
  ##########
  # OSX
  ##########
  build-osx:
    name: Build executable for OSX
    runs-on: macos-latest
    steps:
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v2
    - id: setup-jdk
      name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - id: build
      name: Build distribution
      run: |
        gradle -v
        gradle build
        jpackage --verbose "@config/jpackage.cfg" "@config/jpackage-osx.cfg" --app-version ${{ env.APP_VERSION }}
    - id: upload
      name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        path: ./build/distributions/osx
        name: osx-executable
        retention-days: 1

  ### Download and release the artifacts
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-windows, build-osx]
    steps:

    ### Download executables
    - id: download-windows-executable
      name: Download Windows executable
      uses: actions/download-artifact@v2
      with:
        name: windows-executable
        path: windows
    - id: download-osx-executable
      name: Download OSX executable
      uses: actions/download-artifact@v2
      with:
        name: osx-executable
        path: osx

    ### Create the release
    - id: create-release
      name: Create GitHub release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ github.sha }}
        release_name: release-${{ github.sha }}
        draft: false
        prerelease: false

    ### Upload the artifacts to the release
    - id: release-windows
      name: Release Windows executable
      uses: actions/upload-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: windows/rpg-redesign
        asset_name: windows/rpg-redesign
        asset_content_type: application/x-binary

    - id: release-osx
      name: Release OSX executable
      uses: actions/upload-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: osx/rpg-redesign
        asset_name: osx/rpg-redesign
        asset_content_type: application/x-binary
