name: Build Installers

on:
  workflow_dispatch:

jobs:
  build-windows-installer:
    name: Build Installer on Windows
    runs-on: windows-latest
    steps:
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v2
    - id: setup-jdk
      name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - id: build
      name: Build distribution
      run: |
        gradle -v
        gradle build
        jpackage --verbose "@config/jpackage.cfg" "@config/jpackage-windows.cfg"
    - id: upload-installer
      name: Upload installer
      uses: actions/upload-artifact@v2
      with:
        path: ./build/distributions/rpg-redesign.msi
        name: windows-installer
        retention-days: 1
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-windows-installer]
    steps:

    - id: download-windows-installer
      name: Download Windows installer
      uses: actions/download-artifact@v2
      with:
        name: windows-installer

    - id: create-release
      name: Create GitHub release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ github.sha }}
        release_name: release-${{ github.sha }}
        draft: false
        prerelease: false
    - id: release-windows-installer
      name: Release Windows installer
      uses: actions/upload-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: rpg-redesign.msi
        asset_name: rpg-redesign.msi
        asset_content_type: application/x-binary
